name = "ACEfit"
uuid = "ad31a8ef-59f5-4a01-b543-a85c2f73e95c"
authors = ["Christoph Ortner <christophortner0@gmail.com> and contributors"]
version = "0.0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
